# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

#report: "report/workflow.rst"

pepfile: "config/pep/PBMCs_10x_stellarscope_project_config.yaml"

samples = pep.sample_table

configfile: "config/config.yaml"

rule all:
    input:
        expand("data/{s}_fastqs", s = samples["sample_name"])


include: "rules/download_fastqs.smk"
include: "rules/download_remote.smk"
include: "rules/untar_genome.smk"
include: "rules/index_genome_star.smk"


