# The main entry point of your workflow.
# After configuring, running snakemake -n in a clone of this repository should successfully execute a dry-run of the workflow.

#report: "report/workflow.rst"

pepfile: "config/pep/PBMCs_10x_stellarscope_project_config.yaml"

samples = pep.sample_table

configfile: "config/config.yaml"

rule all:
    input:
        expand("results/completed/{s}_{method}_completed.txt", s = samples["sample_name"], method = ["pseudobulk", "individual"])


include: "rules/download_fastqs.smk"
include: "rules/download_clusters.smk"
include: "rules/download_remote.smk"
include: "rules/untar_genome.smk"
include: "rules/index_genome_star.smk"
include: "rules/get_whitelist.smk"
include: "rules/starsolo_alignment.smk"
include: "rules/samtools_collate.smk"
include: "rules/samtools_cellsort.smk"
include: "rules/split_bam_in_clusters.smk"
include: "rules/telescope_annotation.smk"
include: "rules/stellarscope_pseudobulk.smk"
include: "rules/stellarscope_individual.smk"
include: "rules/stellarscope_clusters.smk"
include: "rules/merge_matrices.smk"
include: "rules/sample_complete.smk"

