# This file should contain everything to configure the workflow on a global scale.
# In case of sample based data, it should be complemented by a samples.tsv file that contains
# one row per sample. It can be parsed easily via pandas.

samples: "config/samples.tsv"

tmpdir: "$TMPDIR"

# remote resources to be downloaded
#
downloads:
  GRCh38.fa.tar.gz:
    url: "https://api.gdc.cancer.gov/data/254f697d-310d-4d7d-a27b-27fbf767a834"
    md5: "3ffbcfe2d05d43206f57f81ebb251dc9"
  gencode38.gtf.gz:
    url: "http://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_human/release_38/gencode.v38.annotation.gtf.gz"
    md5: "16fcae8ca8e488cd8056cf317d963407"

# files for reference genome index
#
sequences:
    genome_tar_gz: "resources/downloads/GRCh38.fa.tar.gz"
    genome_gz: "resources/sequences/GRCh38.fa.gz"

annotations:
    gencode_gz: "resources/downloads/gencode38.gtf.gz"

genome_index:
    star: "resources/star_index/GRCh38_gencode38"

# STAR index parameters
#
splice_junction_overhang: 99
star_index_threads: 32
star_index_mem_mb: 50000
local_tmp: "$TMPDIR"

